<a href="https://colab.research.google.com/github/ayshameharin896/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
a=[1,3,2,4,3]
b=pd.Series(a)
print(b)

0    1
1    3
2    2
3    4
4    3
dtype: int64

In [3]:
a={"Name":["Aysha","Arathi","Aswathy"],"Age":[26,22,27]}
b=pd.DataFrame(a)
print(b)

      Name  Age
0    Aysha   26
1   Arathi   22
2  Aswathy   27

In [8]:
from google.colab import files
uploaded = files.upload()
import pandas as pd

df = pd.read_csv("BLINKIT TRIAL MEASURES.csv")
print(df)

Saving BLINKIT TRIAL MEASURES.csv to BLINKIT TRIAL MEASURES (1).csv
   campaign_id          campaign_name        date target_audience  \
0       548299      New User Discount  05-11-2024         Premium
1       390914        Weekend Special  05-11-2024        Inactive
2       834385         Festival Offer  05-11-2024        Inactive
3       241523             Flash Sale  05-11-2024        Inactive
4       595111       Membership Drive  05-11-2024       New Users
5       176344     Category Promotion  05-11-2024        Inactive
6       875646  App Push Notification  05-11-2024         Premium
7         5516         Email Campaign  05-11-2024         Premium
8       989534       Referral Program  05-11-2024       New Users

        channel  impressions  clicks  conversions    spend  revenue_generated  \
0           App         3130     163           78  1431.85            4777.75
1           App         3925     494           45  4506.34            6238.11
2         Email         7012     370           78  4524.23            2621.00
3           SMS         1115     579           86  3622.79            2955.00
4         Email         7172     795           54  2888.99            8951.81
5           App         4333     421           40  2714.78            6697.88
6         Email         4752     937           21  3584.76            9152.99
7  Social Media         1559     418           68  1457.88            2156.09
8           SMS         3838     911           45  4808.64            8074.17

   roas
0  3.60
1  2.98
2  2.95
3  2.84
4  2.22
5  3.89
6  2.14
7  3.92
8  1.70

In [9]:
df.head()

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,05-11-2024,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,05-11-2024,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,05-11-2024,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,05-11-2024,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,05-11-2024,New Users,Email,7172,795,54,2888.99,8951.81,2.22

In [10]:
df.tail()

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
4,595111,Membership Drive,05-11-2024,New Users,Email,7172,795,54,2888.99,8951.81,2.22
5,176344,Category Promotion,05-11-2024,Inactive,App,4333,421,40,2714.78,6697.88,3.89
6,875646,App Push Notification,05-11-2024,Premium,Email,4752,937,21,3584.76,9152.99,2.14
7,5516,Email Campaign,05-11-2024,Premium,Social Media,1559,418,68,1457.88,2156.09,3.92
8,989534,Referral Program,05-11-2024,New Users,SMS,3838,911,45,4808.64,8074.17,1.70

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        9 non-null      int64
 1   campaign_name      9 non-null      object
 2   date               9 non-null      object
 3   target_audience    9 non-null      object
 4   channel            9 non-null      object
 5   impressions        9 non-null      int64
 6   clicks             9 non-null      int64
 7   conversions        9 non-null      int64
 8   spend              9 non-null      float64
 9   revenue_generated  9 non-null      float64
 10  roas               9 non-null      float64
dtypes: float64(3), int64(4), object(4)
memory usage: 924.0+ bytes

In [12]:
df.describe()

,campaign_id,impressions,clicks,conversions,spend,revenue_generated,roas
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,517474.666667,4092.888889,565.333333,57.222222,3282.251111,5736.088889,2.915556
std,340803.306571,2085.753488,264.151945,21.579955,1265.268675,2734.794456,0.790634
min,5516.000000,1115.000000,163.000000,21.000000,1431.850000,2156.090000,1.700000
25%,241523.000000,3130.000000,418.000000,45.000000,2714.780000,2955.000000,2.220000
50%,548299.000000,3925.000000,494.000000,54.000000,3584.760000,6238.110000,2.950000
75%,834385.000000,4752.000000,795.000000,78.000000,4506.340000,8074.170000,3.600000
max,989534.000000,7172.000000,937.000000,86.000000,4808.640000,9152.990000,3.920000

In [14]:
from google.colab import files
uploaded = files.upload()
import pandas as pd

df = pd.read_excel("BLINKIT MEASURES.xlsx")
print(df)

Saving BLINKIT MEASURES.xlsx to BLINKIT MEASURES (1).xlsx
   campaign_id          campaign_name       date target_audience  \
0       548299      New User Discount 2024-11-05         Premium
1       390914        Weekend Special 2024-11-05        Inactive
2       834385         Festival Offer 2024-11-05        Inactive
3       241523             Flash Sale 2024-11-05        Inactive
4       595111       Membership Drive 2024-11-05       New Users
5       176344     Category Promotion 2024-11-05        Inactive
6       875646  App Push Notification 2024-11-05         Premium
7         5516         Email Campaign 2024-11-05         Premium
8       989534       Referral Program 2024-11-05       New Users

        channel  impressions  clicks  conversions    spend  revenue_generated  \
0           App         3130     163           78  1431.85            4777.75
1           App         3925     494           45  4506.34            6238.11
2         Email         7012     370           78  4524.23            2621.00
3           SMS         1115     579           86  3622.79            2955.00
4         Email         7172     795           54  2888.99            8951.81
5           App         4333     421           40  2714.78            6697.88
6         Email         4752     937           21  3584.76            9152.99
7  Social Media         1559     418           68  1457.88            2156.09
8           SMS         3838     911           45  4808.64            8074.17

   roas
0  3.60
1  2.98
2  2.95
3  2.84
4  2.22
5  3.89
6  2.14
7  3.92
8  1.70

In [15]:
df.head()

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22

In [16]:
df.tail()

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22
5,176344,Category Promotion,2024-11-05,Inactive,App,4333,421,40,2714.78,6697.88,3.89
6,875646,App Push Notification,2024-11-05,Premium,Email,4752,937,21,3584.76,9152.99,2.14
7,5516,Email Campaign,2024-11-05,Premium,Social Media,1559,418,68,1457.88,2156.09,3.92
8,989534,Referral Program,2024-11-05,New Users,SMS,3838,911,45,4808.64,8074.17,1.70

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        9 non-null      int64
 1   campaign_name      9 non-null      object
 2   date               9 non-null      datetime64[ns]
 3   target_audience    9 non-null      object
 4   channel            9 non-null      object
 5   impressions        9 non-null      int64
 6   clicks             9 non-null      int64
 7   conversions        9 non-null      int64
 8   spend              9 non-null      float64
 9   revenue_generated  9 non-null      float64
 10  roas               9 non-null      float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(3)
memory usage: 924.0+ bytes

In [18]:
df.describe()

,campaign_id,date,impressions,clicks,conversions,spend,revenue_generated,roas
count,9.000000,9,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,517474.666667,2024-11-05 00:00:00,4092.888889,565.333333,57.222222,3282.251111,5736.088889,2.915556
min,5516.000000,2024-11-05 00:00:00,1115.000000,163.000000,21.000000,1431.850000,2156.090000,1.700000
25%,241523.000000,2024-11-05 00:00:00,3130.000000,418.000000,45.000000,2714.780000,2955.000000,2.220000
50%,548299.000000,2024-11-05 00:00:00,3925.000000,494.000000,54.000000,3584.760000,6238.110000,2.950000
75%,834385.000000,2024-11-05 00:00:00,4752.000000,795.000000,78.000000,4506.340000,8074.170000,3.600000
max,989534.000000,2024-11-05 00:00:00,7172.000000,937.000000,86.000000,4808.640000,9152.990000,3.920000
std,340803.306571,NaN,2085.753488,264.151945,21.579955,1265.268675,2734.794456,0.790634

In [19]:
df['campaign_name']

0        New User Discount
1          Weekend Special
2           Festival Offer
3               Flash Sale
4         Membership Drive
5       Category Promotion
6    App Push Notification
7           Email Campaign
8         Referral Program
Name: campaign_name, dtype: object

In [20]:
df[['campaign_id','campaign_name']]

   campaign_id          campaign_name
0       548299      New User Discount
1       390914        Weekend Special
2       834385         Festival Offer
3       241523             Flash Sale
4       595111       Membership Drive
5       176344     Category Promotion
6       875646  App Push Notification
7         5516         Email Campaign
8       989534       Referral Program

In [21]:
df.loc[0]

campaign_id                       548299
campaign_name          New User Discount
date                 2024-11-05 00:00:00
target_audience                  Premium
channel                              App
impressions                         3130
clicks                               163
conversions                           78
spend                            1431.85
revenue_generated                4777.75
roas                                 3.6
Name: 0, dtype: object

In [27]:
df["salary"]=[2001,2451,5248,2465,1548,12475,3265,2154,2425]
print(df)

   campaign_id          campaign_name       date target_audience  \
0       548299      New User Discount 2024-11-05         Premium
1       390914        Weekend Special 2024-11-05        Inactive
2       834385         Festival Offer 2024-11-05        Inactive
3       241523             Flash Sale 2024-11-05        Inactive
4       595111       Membership Drive 2024-11-05       New Users
5       176344     Category Promotion 2024-11-05        Inactive
6       875646  App Push Notification 2024-11-05         Premium
7         5516         Email Campaign 2024-11-05         Premium
8       989534       Referral Program 2024-11-05       New Users

        channel  impressions  clicks  conversions    spend  revenue_generated  \
0           App         3130     163           78  1431.85            4777.75
1           App         3925     494           45  4506.34            6238.11
2         Email         7012     370           78  4524.23            2621.00
3           SMS         1115     579           86  3622.79            2955.00
4         Email         7172     795           54  2888.99            8951.81
5           App         4333     421           40  2714.78            6697.88
6         Email         4752     937           21  3584.76            9152.99
7  Social Media         1559     418           68  1457.88            2156.09
8           SMS         3838     911           45  4808.64            8074.17

   roas  salary
0  3.60    2001
1  2.98    2451
2  2.95    5248
3  2.84    2465
4  2.22    1548
5  3.89   12475
6  2.14    3265
7  3.92    2154
8  1.70    2425

In [29]:
df.drop('salary',axis=1)

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22
5,176344,Category Promotion,2024-11-05,Inactive,App,4333,421,40,2714.78,6697.88,3.89
6,875646,App Push Notification,2024-11-05,Premium,Email,4752,937,21,3584.76,9152.99,2.14
7,5516,Email Campaign,2024-11-05,Premium,Social Media,1559,418,68,1457.88,2156.09,3.92
8,989534,Referral Program,2024-11-05,New Users,SMS,3838,911,45,4808.64,8074.17,1.70

In [30]:
df.sort_values("clicks")

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas,salary
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60,2001
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95,5248
7,5516,Email Campaign,2024-11-05,Premium,Social Media,1559,418,68,1457.88,2156.09,3.92,2154
5,176344,Category Promotion,2024-11-05,Inactive,App,4333,421,40,2714.78,6697.88,3.89,12475
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98,2451
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84,2465
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22,1548
8,989534,Referral Program,2024-11-05,New Users,SMS,3838,911,45,4808.64,8074.17,1.70,2425
6,875646,App Push Notification,2024-11-05,Premium,Email,4752,937,21,3584.76,9152.99,2.14,3265

In [31]:
data={'department':['HR','IT','HR','IT'],'salary':[2000,3000,2500,3500]}
a=pd.DataFrame(data)
print(a.groupby('department').mean())

            salary
department
HR          2250.0
IT          3250.0

In [34]:
data={'department':['HR','IT','HR','IT'],'salary':[2000,3000,2500,3500]}
a=pd.DataFrame(data)
a['salary'].sum()

np.int64(11000)

In [35]:
data={'department':['HR','IT','HR','IT'],'salary':[2000,3000,2500,3500]}
a=pd.DataFrame(data)
a['salary'].mean()

np.float64(2750.0)

In [36]:
data={'department':['HR','IT','HR','IT'],'salary':[2000,3000,2500,3500]}
a=pd.DataFrame(data)
a['salary'].min()

2000

In [37]:
data={'department':['HR','IT','HR','IT'],'salary':[2000,3000,2500,3500]}
a=pd.DataFrame(data)
a['salary'].max()

3500